name: yuro_annotation
description: A annotation for yuro_generator.
version: 0.2.0
homepage: https://github.com/YuroLtd/yuro_annotation

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0